openapi: 3.0.0
paths:
  /logs:
    post:
      operationId: LogsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLogRequestDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateLogResponseDto"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      tags:
        - logs
info:
  title: REST API as BFF for Stuart application challenge
  description: Logs REST API
  version: "1.0"
  contact: {}
tags:
  - name: logs
    description: ""
servers: []
components:
  schemas:
    CreateLogRequestDto:
      type: object
      properties:
        job_id:
          type: number
          description: Job ID
          example: "123456"
        message:
          type: string
          description: Message of the log
          example: Courier started a job with ID 123456 - IN PROGRESS
        status:
          type: string
          description: Job status
          example: IN-PROGRESS
      required:
        - job_id
        - message
        - status
    CreateLogResponseDto:
      type: object
      properties:
        job_id:
          type: number
          description: Job ID
          example: "123456"
        message:
          type: string
          description: Message of the log
          example: Courier started a job with ID 123456 - IN PROGRESS
        status:
          type: string
          description: Job status
          example: IN-PROGRESS
        id:
          type: string
          description: ID of the log with UUID format
          example: 123e4567-e89b-12d3-a456-426614174000
        created_at:
          format: date-time
          type: string
          description: Datetime of the log is created folowwing ISO format
          example: 2021-01-01T00:00:00.000Z
      required:
        - job_id
        - message
        - status
        - id
        - created_at
